# Generated by Django 5.2 on 2025-04-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('api_url', models.CharField(max_length=1000, unique=True)),
                ('api_key', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_no',
        ),
        migrations.AddField(
            model_name='member',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('application', models.ManyToManyField(to='GPT.applications')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='department_name',
            field=models.ForeignKey(default='测试部门', on_delete=django.db.models.deletion.SET_DEFAULT, to='GPT.department'),
        ),
    ]
