# Generated by Django 5.2 on 2025-04-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0003_alter_member_options_alter_member_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='validate',
        ),
    ]
