# Generated by Django 5.2 on 2025-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0005_alter_member_department_name_applications_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='member',
        ),
        migrations.AddField(
            model_name='applications',
            name='application_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='applications',
            name='api_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applications',
            name='api_url',
            field=models.CharField(unique=True),
        ),
    ]
