# Generated by Django 5.2 on 2025-04-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0006_remove_applications_member_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
