# Generated by Django 5.2 on 2025-04-21 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0007_rename_applications_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='member',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
