# Generated by Django 5.2 on 2025-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0008_remove_member_application_application_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.CharField(default='Waypoints', max_length=100),
        ),
    ]
