# Generated by Django 5.2 on 2025-04-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0009_application_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='application',
            field=models.ManyToManyField(related_name='app', to='GPT.application'),
        ),
    ]
