# Generated by Django 5.2 on 2025-04-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0010_member_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='application_type',
            new_name='type',
        ),
    ]
