# Generated by Django 5.2 on 2025-04-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0011_rename_application_name_application_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='api_url',
            field=models.CharField(max_length=500),
        ),
    ]
