# Generated by Django 5.2 on 2025-04-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0012_alter_application_api_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_url', models.CharField(max_length=500)),
                ('model_key', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=100)),
            ],
        ),
    ]
