# Generated by Django 5.2 on 2025-04-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0013_model_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_info',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
