# Generated by Django 5.2 on 2025-04-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0014_alter_model_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_info',
            name='model_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
