# Generated by Django 4.2.20 on 2025-05-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0015_model_info_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_info',
            name='model_provider',
            field=models.CharField(default='', max_length=100),
        ),
    ]
