# Generated by Django 4.2.20 on 2025-05-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0016_model_info_model_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_info',
            old_name='name',
            new_name='show_name',
        ),
        migrations.AddField(
            model_name='model_info',
            name='model_providerId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
