# Generated by Django 4.2.20 on 2025-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0017_rename_name_model_info_show_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_info',
            name='model_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
